# Generated by Django 4.2 on 2024-11-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_chatbotconversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotconversation',
            name='response',
        ),
        migrations.AlterField(
            model_name='chatbotconversation',
            name='message',
            field=models.JSONField(default=list),
        ),
    ]
