# Generated by Django 4.2 on 2024-11-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_chatbotconversation_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.JSONField(blank=True),
        ),
    ]
